### PR TITLE
fix: correct title/button issue on synchronous graph widget

### PR DESCRIPTION
**Pull request by gfzdw**
This should correct the title issues that cropped up in the synchronous graph widget.

Desktop:

Screen Shot 2020-11-13 at 5 35 49 PM

Tablet:

Screen Shot 2020-11-13 at 5 36 03 PM

### CODE REVIEW

**Comment by kizniche** [comment]
I'm a fan of compact UIs and ideally I'd like to keep it on the same line. If it can be centered with the buttons aligned to the right, that it preferred to moving the title to the next line.

**Comment by gfzdw** [comment]
I agree. I actually started with your suggestion and moved away from it because, on small screens, the buttons overlay the widget name and obscure it from being read. 

I'll take another look at it in the morning. I'm working on an input for INA219 sensors and should be done with that in the afternoon. I'm just waiting on the sensor to arrive to test my code. 

We may have to set up some media queries within CSS to shrink the buttons from text to icons on the smallest screens.

**Comment by kizniche** [comment]
Thanks for the help. I'm not the best with UI design. I like the idea of shrinking the buttons to icons.

**Comment by gfzdw** [comment]
### Desktop

Desktop

### Tablet / Mobile (collapsed)

Tablet - Collapsed

### Tablet / Mobile (expanded)

Tablet - Expanded

**Comment by kizniche** [comment]
I just tested and that looks and acts great!

**Comment by kizniche** [comment]
Thanks for all the help on that. You've made a really nice design.

**Comment by kizniche** [comment]
I did just notice an issue with overlapping:

Screenshot_2020-11-14 tango - Default Dashboard Dashboard - Mycodo 8 8 8

**Comment by kizniche** [comment]
It's tricky, and I see the tradeoff with having a more true centering or an offset center between the left side and the buttons.

**Comment by gfzdw** [comment]
You may need to do a hard refresh to see the new CSS that addresses that.

**Comment by kizniche** [comment]
Perhaps keeping the buttons collapsed with the icon by default would be better to reduce the likelihood of the text overlapping. I don't see the buttons really needing to always be visible, but they are definitely handy when they're needed.

**Comment by kizniche** [comment]
Okay, let me test some more in a new browser.

**Comment by gfzdw** [comment]
If the issue persists, I'd recommend we do what you mentioned: keep the buttons collapsed until they're needed. I set the breakpoint at 992px, so the only time there'd be an overlapping button issue is when the title of the widget is very long.

**Comment by kizniche** [comment]
Just tested again, and same result. This widget is rather narrow, but the data suits it being narrow. The title starts to overlap right before the breakpoint. Seems it being collapsed by default might be the best solution for graph cases like mine.

**Comment by gfzdw** [comment]
Okay, I'm going to collapse the buttons into the burger menu. I think that'll look cleaner anyways, and people know what that icon means.

**Comment by gfzdw** [comment]
As a personal preference, I chose to have the buttons fly out to the left of the burger menu button. If you'd prefer to have it in a separate DIV below the widget title, just let me know. Thanks!

**Comment by gfzdw** [comment]
I should have tested this on mobile for pushing the branch. It's going to look better having the buttons in a separate DIV. Especially on mobile. Give me a couple of minutes to fix and then this should be done.

**Comment by gfzdw** [comment]
## Collapsed

Screen Shot 2020-11-14 at 11 54 45 AM

## Expanded

Screen Shot 2020-11-14 at 11 54 59 AM

**Comment by kizniche** [comment]
I notice the legend is being pushed out of the bottom and partially hidden. When you mentioned appearing to the left of the burger, was that because it appeared over the title text?

Screenshot_2020-11-14 tango - Default Dashboard Dashboard - Mycodo 8 8 8-2

**Comment by gfzdw** [comment]
Yeah, it was over the widget title.

**Comment by kizniche** [comment]
From a usability standpoint, I think that would be better than obscuring part of the graph. I often have several series that I refer to the legend for. Is it possible to push the title over if the buttons appear to the left of the burger, rather than going over the title?

**Comment by gfzdw** [comment]
Okay, I feel like 9ccf5a6 is probably what you're after.

# Desktop (expanded)

Screen Shot 2020-11-14 at 4 46 55 PM

# Mobile (collapsed)

Screen Shot 2020-11-14 at 4 46 36 PM

# Mobile (expanded)

Screen Shot 2020-11-14 at 4 46 43 PM

**Comment by kizniche** [comment]
It looks and works great! Thanks for all the work.

**Pull request merged**
