### PR TITLE
Added support for SHT1x/SHT7x sensors by Senserion

### PR DESCRIPTION
**Pull request by MountAthos**
Added support for SHT1x/SHT7x sensors by Senserion
Extended Web Admin features for SHT sensors
+ Voltage selection
+ Clock Pin selection
+ keeping selected value in focus in Admin panel
+ assign default Voltage for new added Sensors
+ Add debugging info for SHT sensors
Extended DB arrays and database tables where necessary

### CODE REVIEW

**Comment by MountAthos** [comment]
Let me check, will take some time.
 Not all HT sensors have clock pin or voltage setting - This is IF condition working only with SHT (tested already)
> For the rest i need some time to check

**Comment by kizniche** [comment]
Looking good!

**Comment by kizniche** [comment]
I'm going to need a block of time to be able to do some testing after the merge, so I'm not going to merge tonight. Maybe tomorrow. I think everything will be fine, but I want to have enough room to fix something if it isn't.

**Comment by MountAthos** [comment]
No problem.
If you find anything i have missed, just tell me - i will fix that.
So far from what i have seen or thought - was fixed.
But nobody is perfect, especially me is not :)
I will later work on original driver and will add it to branch, because of for Raspberry Pi, which is using 3.3V for sensor, the calculations are not 100% correct. I have add already everything for 3.3V support and i have tested it also too in Mycodo with fixed driver.
I will think the most efficient way to do and then upload the way i have found into branch.
I was thinking on self detection of SHT sensors, but this is already luxury :) will think of it a little later.
-> Any approx. ideas on when the new Framework may be ready?
(Asking because i will start to work on another GUI for the end users and administrators)
And the question also if you need it..

**Comment by kizniche** [comment]
What about the SQL stuff?

restricted.php
Line 1735: Should this be SQLITE3_FLOAT?

update-database.py
Line 613 and 675: Should this be REAL?

**Comment by kizniche** [comment]
I'm not sure about when the new framework will be operational, but it will probably be in the order of a few weeks, not a few months, but that is an estimation.

**Comment by MountAthos** [comment]
613 and 675 are TEXT (string) values.. nothing wrong with it..
1735 - no, shall be STRing

**Comment by kizniche** [comment]
What are some examples of the values?

**Comment by MountAthos** [comment]
3.3V
2.5V
2V etc

**Comment by kizniche** [comment]
Is the V necessary? Can it just become a float and if the V is necessary, add it later?

**Comment by MountAthos** [comment]
The full string is
sht pin clock_pin voltage

**Comment by MountAthos** [comment]
V is necessary direct in driver.
The string it shall get is exact 
> 3.3V
Well, in fact of course "V" could be add afterwards :)
But at this specific point... necessary?
I didn't see yet other sensors with this value for RH calculation

**Comment by MountAthos** [comment]
I go to rest... its 4 AM at my side.. i need at least 1-2 hours to be half-way alive for tomorrow work :)
I have to stand up at 5.30 AM lol :)

**Comment by kizniche** [comment]
Eek! Go rest. Thanks for the hard work. I'll merge and test soon.

**Comment by MountAthos** [comment]
I shall thank you :)
Great Project - amazing Joy to make and to help

**Comment by kizniche** [comment]
Merged, tested, and all looking good. I had the idea to include the python module update/install command in the post-update shell script so no one's system breaks from the unmet dependency (sht python module). I'm not sure why I didn't do this sooner (probably because I didn't know about the --upgrade option).

**Comment by MountAthos** [comment]
Hi, tell me, the Dew Point is used in PiD calculation for RH (humidity)
sensor?

I didnt check this in code, but interesting is that SHT75 is using own DEW
output..
I think if PiD uses it for real calculation, i can integrate the SHT75 dew
point output and by wish via web panel to be switchable

**Comment by kizniche** [comment]
Dew Point is not regulated by PID. As dew point is calculated from both humidity and temperature, this would be complex to code a PID controller to manipulate this condition.

**Pull request merged**
