### PR TITLE
fix docker setup

### PR DESCRIPTION
**Pull request by deargle**
needed for command `make`

### CODE REVIEW

**Comment by deargle** [comment]
fyi I'm tinkering with launching a pretty-much-free personal public mycodo server on a google compute platform (gcp) free-tier box, see compute-engine section in https://cloud.google.com/free/docs/gcp-free-tier#free-tier-usage-limits. GCP just because that's what I'm most familiar with.

**Comment by kizniche** [comment]
Thanks. Let me know how it goes.

**Comment by deargle** [comment]
@kizniche I'm hitting a pip path problem, it might help me to at least think it out loud, not asking you to fix this as I know you don't support the docker feature.

* docker/setup.sh sets up the virtual environment, here: herehttps://github.com/kizniche/Mycodo/blob/8eb3a4267dec667d4d2e7950c7ff1d167318baa9/docker/setup.sh#L22
* scripts/dependencies.sh uses the environment's `pip3`, *but this fails* because the virtual environment's pip specifies a full _docker container host_ path to the python exec, rather than to the docker-container-specific env path https://github.com/kizniche/Mycodo/blob/8eb3a4267dec667d4d2e7950c7ff1d167318baa9/mycodo/scripts/dependencies.sh#L28 

For example, I get the following error message when trying to install paho:

```shell script
[2021-06-22 02:58:46] #### Installing/updating paho-mqtt==1.5.1 (pip-pypi)
[2021-06-22 02:58:46] /home/mycodo/mycodo/scripts/dependencies.sh: /home/mycodo/env/bin/pip3: /home/dave_eargle/Mycodo/env/bin/python: bad interpreter: No such file or directory
```

... where `/home/dave_eargle/Mycodo` is my install location on the host, and `/home/mycodo` is a path within the docker container.

I think this can be fixed by calling `python -m pip` instead of `pip` directly -- with this, whichever pip is used will be one that can easily find the right python exec, having been invoked by it. Shouldn't break anything outside of docker...

Do you see an immediate better approach to fixing this?

Also btw the Dockerfile needs `RUN /home/mycodo/mycodo/scripts/upgrade_commands.sh compile-mycodo-wrapper` because otherwise the wrapper never gets compiled. Just noting this down.

**Comment by kizniche** [comment]
Are you using docker-compose to build?

**Comment by deargle** [comment]
> Are you using docker-compose to build?

Yes. Using `make build`

**Comment by kizniche** [comment]
I understand the issue now. Are you able to build with the solution you mentioned?

**Comment by kizniche** [comment]
Perhaps a better way would be to delete the env directory in the docker volume after copying the Mycodo directory, then build the virtualenv again inside the volume.

**Comment by deargle** [comment]
> I understand the issue now. Are you able to build with the solution you mentioned?

Trying now. I'm not a smart man so I ran `make clean`, which removed all the docker cache steps from _everything_, so I have to wait a while to retry.

> Perhaps a better way would be to delete the env directory in the docker volume after copying the Mycodo directory, then build the virtualenv again inside the volume.

Yes, that would work too. _Also_ switching to `python -m pip` would future-proof if ever there are multiple python versions etc.

**Comment by deargle** [comment]
> Perhaps a better way would be to delete the env directory in the docker volume after copying the Mycodo directory, then build the virtualenv again inside the volume.

Does this directory need to be created at all outside of the docker containers? Maybe we just remove the call to it in docker/setup.sh. Then each container would create it within its own filesystem as-needed.

**Comment by kizniche** [comment]
Can you explain where you are proposing that line change? Does that still keep the execution within the virtualenv?

**Comment by kizniche** [comment]
>Does this directory need to be created at all outside of the docker containers? Maybe we just remove the call to it in docker/setup.sh.

It's really only necessary to ensure docker-compose is installed.

**Comment by deargle** [comment]
> Can you explain where you are proposing that line change? Does that still keep the execution within the virtualenv?

For example, the following line: https://github.com/kizniche/Mycodo/blob/8eb3a4267dec667d4d2e7950c7ff1d167318baa9/mycodo/scripts/dependencies.sh#L28 

would become:

`"${INSTALL_DIRECTORY}"/env/bin/python3 -m pip install --upgrade "${2}"`

**Comment by kizniche** [comment]
I just like working within virtualenvironments and prefer that over changing system-wide packages.

**Comment by kizniche** [comment]
If your change works, that sounds like a good solution.

**Comment by kizniche** [comment]
Better change line 36 as well.

**Comment by deargle** [comment]
Yes, the solution worked... now on to the next problem! I'll submit one big PR to get docker working when I'm done.

**Comment by deargle** [comment]
Yikes, okay, yes that led to the package being installed for the environment python, but the docker container is running `gunicorn` under a _different_ python version that doesn't have access to that environment's packages. So trying to add the input complains about it not being installed.

I solved the latter by having the docker-compose COMMAND invoke gunicorn and python via the env version. PR incoming.

**Comment by deargle** [comment]
Okay, done, I think! This _shouldn't_ impact raspberry pi stuff, but I don't have one to test :-(

The single-line summary of changes: 
* make _every_ python-related package invocation reference the virtualenv python binary. This includes the docker-compose CMD's.
* change some container-name references of `flask` => `mycodo_flask`
* invoke a run of `compile-mycodo-wrapper` in the Dockerfile

I think the memory usage might be slightly too high for the GCP free tier, though. I was running out while testing and debugging, but maybe with these things fixed, it will run smoothly... I'm showing ~487MB used across the four docker containers -- influxdb, mycodo_daemon, mycodo_flask, and nginx, and the free tier limit is 614 MB.

Also note that I haven't tested anything beyond adding a mqtt input. That is, I haven't done any subscribing or publishing yet. But at least mycodo is letting me get as far as (1) installing missing paho dependency, (2) finding that new dependency, and (3) letting me add the input.

**Comment by Mibu92000** [comment]
Thank you very much mom looking for the doctor right now for that I really do appreciate itSent from my Galaxy
-------- Original message --------From: Dave Eargle ***@***.***> Date: 6/22/21  3:24 AM  (GMT-05:00) To: kizniche/Mycodo ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [kizniche/Mycodo] fix docker setup (#1034) 
Okay, done, I think! This shouldn't impact raspberry pi stuff, but I don't have one to test :-(
The single-line summary of changes:

make every python-related package invocation reference the virtualenv python binary. This includes the docker-compose CMD's.
change some container-name references of flask => mycodo_flask
invoke a run of compile-mycodo-wrapper in the Dockerfile

I think the memory usage might be slightly too high for the GCP free tier, though. I was running out while testing and debugging, but maybe with these things fixed, it will run smoothly... I'm showing ~487MB used across the four docker containers -- influxdb, mycodo_daemon, mycodo_flask, and nginx, and the free tier limit is 614 MB.
Also note that I haven't tested anything beyond adding a mqtt input. That is, I haven't done any subscribing or publishing yet. But at least mycodo is letting me get as far as (1) installing missing paho dependency, (2) finding that new dependency, and (3) letting me add the input.

**Comment by Mibu92000** [comment]
I'm so sorry I just got back to my phone if you want you can text me on the phone a popular Lottie's you to get out of me with some reason the notifications for the emails are off and I can't get him back on and just John hurry up and get what I can get done do you get rid of ours and get rid of whoever was control of on device so I can actually be able to move 4 with a progress on becoming a developer I really wouldn't like to work with you if that's green possible anywaySent from my Galaxy
-------- Original message --------From: Dave Eargle ***@***.***> Date: 6/21/21  11:48 PM  (GMT-05:00) To: kizniche/Mycodo ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [kizniche/Mycodo] add package `build-essential` (#1034) 

I understand the issue now. Are you able to build with the solution you mentioned?

Trying now. I'm not a smart man so I ran make clean, which removed all the docker cache steps from everything, so I have to wait a while to retry.

Perhaps a better way would be to delete the env directory in the docker volume after copying the Mycodo directory, then build the virtualenv again inside the volume.

Yes, that would work too. Also switching to python -m pip would future-proof if ever there are multiple python versions etc.

**Comment by kizniche** [comment]
Thanks for the updated PR. I haven't forgotten about it, I just haven't had the time to test if it works outside docker on a Pi.

**Comment by kizniche** [comment]
That RAM usage seems pretty high. We might be able to make some tweaks to reduce it. I'll see if I can devote some time this weekend to test some things.

**Comment by deargle** [comment]
nw and no rush. I'll look at RAM usage too. I want to add a secured mqtt broker container on top, with the "secure" part coming from a letsencrypt cert. So the more memory-efficient everything is, the more likely it is to fit on the free tier.

**Comment by kizniche** [comment]
All working fine on a Pi. Thanks again for the work getting docker working again. I'll do some research and see if we can reduce that RAM usage.

**Comment by kizniche** [comment]
Could you provide a brief overview to get set up on the GCP?

**Comment by deargle** [comment]
Sure. I can elaborate more, let me know if you need it. 

Assuming:
* you've already signed up for a gcp account
* you already created a project where you want your gcp instance to live

go to [console.cloud.google.com](https://console.cloud.google.com), select your project, and navigate to the `/compute/instances` route, see screenshot below. (Hamburger, Compute Engine submenu, "VM Instances" sub menu.) You might need to "enable" some gcp APIs -- you'll be prompted if necessary.


image

create a new instance. 

* To be on the free tier, you need to use an "f1-micro" instance, which is only available on the "N1" series. 
* And you need to be using HDD, which is a "standard persistent disk", _not_ the default "balanced persistent disk." I'm leaving the default Debian 10 Buster image. I boost disk size to 30 GB. Shown in screenshot. 
* Tick the boxes to allow HTTP and HTTPS through the gcp firewall (screenshot 2 below).
* I leave all other defaults.
* click the fatty "create" button

image

image

When your new instance shows it's ready, click the SSH button to get a browser-based ssh connection. GCP will auto-connect you to your instance without you having to authenticate further, since you're logged in to a google account that has admin access to the instance you just created.

Then my first steps are to:

```
sudo apt update && sudo apt install git
git clone https://github.com/kizniche/Mycodo.git
cd Mycodo/docker
sudo ./setup.sh dependencies
sudo usermod -aG docker $USER
```

Then close the popup and get a new connection. Then, get back into the docker directory, and `make build`, but I actually prefer running docker-compose myself, so I do:

```
alias dc="../env/bin/docker-compose"
dc up -d
```

etc

**Comment by kizniche** [comment]
Thanks for the detailed steps! When I select the CPU/HDD options, it says it will cost $5.08/month. Is this expected?

Screenshot 2021-06-24 at 22-26-09 Google Cloud Platform

**Comment by deargle** [comment]
You know, I _think_ it's okay to ignore that message. There's also the grey below that says "the first 720 hours this month are free." I think the cost estimate is ignoring that, because they can't know if you're already running an f1-micro, or if you plan to run 2 of them. If you ran 2 nonstop for a month, then each would consume its own ~720 hours, and the first would be free, but for the second you'd be paying the $5.08 monthly estimate for the other one. Or rather, you'd burn through your 720 hours by the middle of the month if you were running 2, and you'd be paying for the second 720 combined hours in the second half of the month. They don't care how many instances you run, just the total number of running hours. And your 30 GB HDD can equivalently be spread out.

**Comment by deargle** [comment]
Here's memory usage before doing any docker stuff:

```shell
dave_eargle@instance-1-f1-micro:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:            583         112         139           1         331         375
Swap:             0           0           0
```

after running setup.sh dependencies (probably the result of the docker engine running):

```shell
dave_eargle@instance-1-f1-micro:~/Mycodo/docker$ free -mh
              total        used        free      shared  buff/cache   available
Mem:          583       180Mi          85       1.0Mi       316Mi       305Mi
Swap:            0          0B           0
```

after running `docker-compose up -d`:

```shell
dave_eargle@instance-1-f1-micro:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:            583         382          44           3         156         106
Swap:             0           0           0
```

**Comment by kizniche** [comment]
Building! Well, those container RAM usages actually look good. We may need to look into whether there are any Linux services that we can turn off.

**Comment by kizniche** [comment]
Hmm. I'm not having any luck reducing RAM usage. I'll keep trying, but creating a swap seems like a nice solution. https://geekbacon.com/2015/03/04/how-to-create-a-swap-file-on-google-compute-engine-virtual-machines/

**Comment by deargle** [comment]
On my end, mosquitto mqtt broker is a memory hog, even when not doing
anything. Won't work to run it alongside mycodo on an f1-micro.

**Comment by deargle** [comment]
fyi I'm moving to DigitalOcean $5 per month droplet. Way better than gcp's f1-micro offering. 1GB RAM, 1 CPU, 25 GB SSD. 

image

I'm writing a guide, will share later. letsencrypt for ssl certs, used by mycodo and also by a secure MQTT broker, all in docker.

**Comment by kizniche** [comment]
What about after adding a small swap?

**Comment by deargle** [comment]
Ah! I forgot to try the swap. May go back and try, because $5 per month still adds up.

**Comment by kizniche** [comment]
I just added 30 inputs and started digging into the swap a bit. Still snappy.

```
kg@mycodo-test-01:~$ free -h -t
              total        used        free      shared  buff/cache   available
Mem:          583Mi       405Mi        54Mi       1.0Mi       122Mi        85Mi
Swap:         2.0Gi       136Mi       1.9Gi
Total:        2.6Gi       542Mi       1.9Gi
```

**Comment by deargle** [comment]
Hmm l'll try doing mosquitto again. It wasn't even getting past building for me, kept running out of memory. Maybe it's just slow on startup and then chills out. But your findings are great news!

**Comment by kizniche** [comment]
Are you using ```apt get install mosquitto```?

**Comment by deargle** [comment]
No, using the docker container. My notes-in-progress -- https://github.com/deargle/hydro-notes/tree/main/mosquitto

**Comment by deargle** [comment]
TIL the necessity of at least _some_ swap. Never appreciated it before. Working for me!

**Comment by deargle** [comment]
Is there a reason that influxdb's ports 8083 and 8086 -- and the daemon's 9090 -- need to be open to the world, as opposed to just open between docker containers on the same network? Obviously 80 and 443 need to be world-open.

```
CONTAINER ID   IMAGE             COMMAND                  CREATED             STATUS             PORTS                                                                                                                             NAMES
c4a511789833   docker_nginx      "nginx -g 'daemon of…"   About an hour ago   Up About an hour   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp                                                          nginx
7390f87ff927   app               "bash -c 'PYTHONPATH…"   About an hour ago   Up About an hour   0.0.0.0:9090->9090/tcp, :::9090->9090/tcp                                                                                         mycodo_daemon
98f6bffb6fbc   app               "/home/mycodo/env/bi…"   About an hour ago   Up About an hour                                                                                                                                     mycodo_flask
4db4470bb032   docker_influxdb   "/entrypoint.sh /bin…"   About an hour ago   Up About an hour   0.0.0.0:8083->8083/tcp, :::8083->8083/tcp, 0.0.0.0:8086->8086/tcp, :::8086->8086/tcp, 0.0.0.0:8090->8090/tcp, :::8090->8090/tcp   influxdb
```

**Comment by kizniche** [comment]
No, I believe that was done when I was learning how to use docker-compose and I didn't know any better.

**Comment by kizniche** [comment]
I received an email recently:

>We’ve identified that you’re using an F1-micro instance that is a part of the Compute Engine Free Tier. As we improve the experience of the Free Tier, we will be introducing the E2-micro VM, which is a part of a second generation VM family. It offers additional resources for your use, specifically 0.25 vCPU (which burst to 2 vCPU periodically) and 1 GB of RAM.
>
>What do I need to know?
>The Free Tier F1-micro VM is changing to the E2-micro VM as the VM to use for free. On August 1, 2021, E2-micro Free Tier will be introduced. Follow these steps to change your machine type to E2-micro to avoid incurring charges for continuing to use F1-micro after August 31, 2021.
>
>What do I need to do?
>Starting August 1, 2021, change the machine type from F1-micro, or stop your existing F1-micro instance and begin using a E2-micro instance. VMs created with either method will automatically have the Free Tier discount applied to them. The supported regions will remain the same.

**Comment by deargle** [comment]
Yeah I got that too, they're probably doing it to try to knock digitalocean
off the market. It's good news though!

**Pull request merged**
