### PR TITLE
Update upgrade_commands.sh

### PR DESCRIPTION
**Pull request by ddominikp**
Changed virtualenv to venv as the first one does not seem to be working on raspberry pi 64 bit os bullseye. Also to maintain consistency bin/python changed to bin/python3.

python3 -m venv --system-site-packages "${MYCODO_PATH}"/env

### CODE REVIEW

**Comment by kizniche** [comment]
Why did you add --system-site-packages? This breaks certain parts of Mycodo and was removed in https://github.com/kizniche/Mycodo/commit/60993eb07c089372f594b4f8723349476e5a7774

**Comment by ddominikp** [comment]
This made it work on my specific build of Raspberry Pi OS (64 bit) Bullseye. Otherwise I ran into missing modules, but first of all missing virtual environment. If it is ensured that the virtual environment is self-contained then this can be removed.

**Comment by kizniche** [comment]
I installed recently on Raspberry Pi OS 64-bit and didn't have any issues. What issues are you referring to?

**Comment by kizniche** [comment]
With regard to the changes you just made in https://github.com/kizniche/Mycodo/pull/1176/commits/8c822427d3ee5c6ce339ca50f3c2efcebd1995e4, any time update-pip3 is called, setup-virtualenv has already been called immediately before it, so adding another check for the virtualenv is not necessary.

**Comment by kizniche** [comment]
Perhaps opening an issue would be better than having a runaround in a PR.

**Comment by ddominikp** [comment]
Regarding my issues, the setup.log was as below (the important part of it).

So for me it looks like an issue with virtual environment creation. I tried using the raw command from upgrade_commands.sh but it seems that it is not doing anything at all. Importantly, the way I upgraded PiOS from buster to bullseye was by sources.list update and apt full-upgrade. Before that upgrade, the Mycodo was working fine. Somewhere along the line I ran into an issue with missing pybabel package (probably because environment was not set up properly in the previous step). To solve this I installed python3-babel package and when creating the environment I ensured that at least it has access to pybabel.

Regarding the additional python env folder check: I added it since it is also present in update-pip3-packages, which also comes after setup-virtualenv (see below). Maybe a neater way would be to move virtual environment existence checking to a separate function.

```
${INSTALL_CMD} setup-virtualenv 2>&1 | tee -a "${LOG_LOCATION}"
${INSTALL_CMD} update-pip3 2>&1 | tee -a "${LOG_LOCATION}"
${INSTALL_CMD} update-pip3-packages 2>&1 | tee -a "${LOG_LOCATION}"

```
> #### Mycodo installation began Wed 13 Apr 02:46:25 CEST 2022
> 
> #### Checking if swap size is 100 MB and needs to be changed to 512 MB
> #### Swap not currently set to 100 MB. Not changing.
> 
> #### Updating apt repositories
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> Hit:1 http://deb.debian.org/debian bullseye InRelease
> Hit:2 http://deb.debian.org/debian bullseye-updates InRelease
> Hit:3 http://archive.raspberrypi.org/debian bullseye InRelease
> Hit:4 http://deb.debian.org/debian bullseye-proposed-updates InRelease
> Hit:5 http://deb.debian.org/debian bullseye-backports InRelease
> Hit:6 https://repos.influxdata.com/debian bullseye InRelease
> Reading package lists...
> Building dependency tree...
> Reading state information...
> All packages are up to date.
> 
> #### Uninstalling apt version of pip (if installed)
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> Reading package lists...
> Building dependency tree...
> Reading state information...
> Package 'python-pip' is not installed, so not removed
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> 
> #### Installing prerequisite apt packages and update pip
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> Reading package lists...
> Building dependency tree...
> Reading state information...
> E: Unable to locate package python-cffi-backend
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> Reading package lists...
> Building dependency tree...
> Reading state information...
> gawk is already the newest version (1:5.1.0-1).
> g++ is already the newest version (4:10.2.1-1).
> gcc is already the newest version (4:10.2.1-1).
> git is already the newest version (1:2.30.2-1).
> libi2c-dev is already the newest version (4.2-1+b1).
> libffi-dev is already the newest version (3.3-6).
> logrotate is already the newest version (3.18.0-2).
> moreutils is already the newest version (0.65-1).
> netcat is already the newest version (1.10-46).
> nginx is already the newest version (1.18.0-6.1).
> python3 is already the newest version (3.9.2-3).
> python3-dev is already the newest version (3.9.2-3).
> rng-tools is already the newest version (5migrate1).
> python3-setuptools is already the newest version (52.0.0-4).
> sqlite3 is already the newest version (3.34.1-3).
> wget is already the newest version (1.21-1+deb11u1).
> python3-pip is already the newest version (20.3.4-4+rpt1).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
> Requirement already satisfied: pip in /usr/local/lib/python3.9/dist-packages (22.0.4)
> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
> 
> #### Checking python 3 virtualenv
> #### Virtualenv doesn't exist. Creating...
> Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
> Requirement already satisfied: virtualenv==20.7.0 in /usr/local/lib/python3.9/dist-packages (20.7.0)
> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
> 
> #### Updating pip
> /home/mao/Mycodo/mycodo/scripts/upgrade_commands.sh: line 456: /home/mao/Mycodo/env/bin/python: No such file or directory
> 
> #### Installing pip requirements
> 
> ## Error: Virtualenv doesn't exist. Create with /home/mao/Mycodo/mycodo/scripts/upgrade_commands.sh setup-virtualenv

**Comment by kizniche** [comment]
>the way I upgraded PiOS from buster to bullseye

Okay, this is your problem. This way of upgrading is discouraged by debian. ubuntu, etc. so your issue is likely the result of doing this. Rather than attempting to change Mycodo to work on your upgraded system, you should see if installing the OS cleanly causes the issue. If it doesn't, then I'd say this PR is unnecessary and this really only applies to your system.

**Comment by ddominikp** [comment]
Fair point. I will revert back some time later (most likely tomorrow) after a clean install - which I was trying to avoid. Thank you for the quick replies. 

Cheers for creating Mycodo!

**Comment by kizniche** [comment]
You can install from a backup, or if you tar ~/Mycodo then extract to the new OS install, then run install/setup.sh. You can also export your settings, then import them into a new Mycodo install. All your config will be preserved, but no data will be preserved. You can attempt to export the measurement data and then import it back into the newly installed Mycodo, but this is an experimental feature.

**Comment by ddominikp** [comment]
Hello,

I did a fresh install using headless Raspberry Pi OS 64-bit (bullseye). Mycodo installed without any issues. Thank you for looking at my situation in such a short amount of time. 

Now regarding this pull request do you think it makes sense to at least unify all python calls to python3? Or is there any specific reason why every now and then python calls are without "3"s. Same with additional python env folder check - it makes the install script output more verbose, should something fail. Thoughts?

**Comment by kizniche** [comment]
>do you think it makes sense to at least unify all python calls to python3?

Perhaps, but python is a symlink to python3 (or whichever version is used), so if/when python 4 is released, it may cause issues if "3" is hard-coded.

>additional python env folder check - it makes the install script output more verbose, should something fail. Thoughts?

I think adding the "setup-virtualenv" command before these run could be beneficial.

I'm looking through and will make some changes. I plan to make a bugfix release tonight that will incorporate these changes as well.

**Pull request closed without merging**
