### PR TITLE
named conditionals 

### PR DESCRIPTION
**Pull request by Cabalist**
This code is a test to see if you would be open to it.  I see a lot of conditionals that are difficult to understand because I am not familiar with the pin settings.  This particular function ```read_relay``` has two conditions that if either are true the relay is considered 'on'.   Rather than have the magic numbers in the conditional I am thinking that you could name these.   Something like 'relay_engaged_down' or 'relay_engaged_up'...  I am taking a wild guess here, that probably isn't what is happening.

If we can break some of the longer lines up into local variables I believe the code could be much easier to read.

### CODE REVIEW

**Comment by Cabalist** [comment]
Hmmm...  Is this a ```relay_id``` instead of a ```relay```?  Just like ```sensor_id```?

**Comment by kizniche** [comment]
Yup, `relay_id` would be more appropriate.

I like the readability. Each relay can either be active from a HIGH or a LOW signal. `relay_trigger` is set to 0 (requiring LOW signal) or 1 (requiring HIGH signal).

**Comment by kizniche** [comment]
I'm thinking this may be a better way to do it, but open to suggestions:
```
def read_relay(relay):
    """
    Read the state of a relay

    :param relay:
    :type relay:
    :return: State of the relay as a string.  Either 'on' or 'off'
    :rtype: str
    """
    relay_active = (relay_trigger[relay - 1] == 0 and GPIO.input(relay_pin[relay - 1]) == 0) or
                    (relay_trigger[relay - 1] == 1 and GPIO.input(relay_pin[relay - 1]) == 1)

    if relay_active:
        return "on"
    else:
        return "off"
```

**Comment by kizniche** [comment]
Actually, I like your method better...

```
def read_relay(relay_id):
    """
    Read the state of a relay

    :param relay_id:
    :type relay_id:
    :return: State of the relay as a string.  Either 'on' or 'off'
    :rtype: str
    """
    relay_active_low = relay_trigger[relay_id - 1] == 0 and GPIO.input(relay_pin[relay_id - 1]) == 0
    relay_active_high = relay_trigger[relay_id - 1] == 1 and GPIO.input(relay_pin[relay_id - 1]) == 1

    if relay_active_low or relay_active_high:
        return "on"
    else:
        return "off"
```

**Pull request merged**
