### PR TITLE
Flask UI isolation

### PR DESCRIPTION
**Pull request by etiology**
### First Steps towards more manageable views
Currently the ```app.py``` module (previously mycodo_flask.py) is **1,942 lines** long.  Errors and issues occurring *anywhere* in the previous ```mycodo_flask.py``` module can bring down the entire front end since all of the views all in the same file.  By taking steps to separate these views into logical [blueprints](http://maximebf.com/blog/2012/11/getting-bigger-with-flask/) the code will become more robust and easier to maintain.

#### What this pull request contains
 - The flask resources were moved into their own package
 - New tests were created to verify that some urls get redirected to the login page (more tests are still needed)
 - Updated the few areas of install script that needed to change due to the new package
 - Updated README with the new package structure

------------
#### How might mycodo look with blueprints?
Imagine if the mycodo_flask package looked like this (notice the ```systemctl``` package):
```
│   ├── mycodo_flask - HTTP server files (Flask)
│   │   ├── ssl_certs - Location of HTTP SSL certificates
│   │   ├── static - Static files reside (images, css, js, etc.)
│   │   ├── templates - Flask HTML templates
│   │   │   └── ...
│   │   ├── systemctl
│   │   │   └── views.py
│   │   └── (more UI sections in packages, each with their own view.py using blueprints...
... rest of packages
```

Examine the current version of the ```/systemctl``` url.
``` python
@app.route('/systemctl/<action>')
def computer_command(action):
    """Execute one of several commands, as root"""
    if (not session.get('logged_in') and
        not flaskutils.authenticate_cookies(USER_DB_PATH, Users)):
        return ('', 204)
    try:
        control = DaemonControl()
        return control.system_control(action)
    except:
        return '0'
```

Now here is the the same route in a blueprint:
``` python
from flask import (Blueprint)
blueprint = Blueprint("users", __name__, url_prefix='/systemctl', static_folder="../static")

@blueprint.route('/<action>')
def computer_command(action):
    """Execute one of several commands, as root"""
    if (not session.get('logged_in') and
        not flaskutils.authenticate_cookies(USER_DB_PATH, Users)):
        return ('', 204)
    try:
        control = DaemonControl()
        return control.system_control(action)
    except:
        return '0'
```

Later the app blueprint can be registered on the app after the app is instantiated:
```
def register_blueprints(app)
    """ A function that registers all of the blueprints in mycodo to the app """
    app.register_blueprint(systemctl.views.blueprint)
    app.register_blueprint(<other blueprints>)
    ...
```

### CODE REVIEW

**Comment by kizniche** [comment]
This looks much cleaner than how I was doing it. Thanks.

Has this been tested to work and is all good to merge? I'm not currently in a position to test after I merge, so I'll await confirmation or until I get access my development Pi to test after the merge.

**Comment by etiology** [comment]
Well I tested it on my pi but I haven't played with mycodo as much as you have. I also don't have anything complicated set up. 

I didn't start with a clean pi. I reused the databases I had previously. If you have any pointers that you do when testing new code I'd love to hear it. Here is what I did:  

  - I disabled the previous mycodo system task via systemctl 
  - killedall apache2
  -  I then verifies the daemon was killed too
  - pushed new code to the pi
  - ran the setup.sh script with the new changes
  - logged in to the UI and started loading pages, graphs, and adding CPU sensors. 


I can start with a clean os but it will have to wait until tonight. What are your thoughts? I'm not using ssl yet. That moved too but I feel that I updated everything.

**Comment by kizniche** [comment]
It looks like everything works after the update, except the ssl cert directory remained under frontend/ so I had to add a few lines to the post-update.sh script to move that folder to mycodo_flask/

**Comment by etiology** [comment]
That's a really good catch. The ssl file that would have previously been there slipped my mind.

**Comment by kizniche** [comment]
I don't really have any good pointers. I just make sure whatever new feature I'm adding works, then load a few pages, then, if I was modifying a feature or changed something related to a different feature, I would test that area to make sure I didn't break it. This is not very methodical at all.

Then, I push the update, and immediately update another of my systems (as I can't update the system I was developing on). If there's an issue, I find the solution either on my dev system or the system I just updated, then push another update from my dev system. Then, I update another of my systems to see if it updates properly. Rinse, repeat, until the update and feature works. If I run out of systems then I may be in trouble because I no longer have a naive system to update from. I could always restore a backup that happens during the update process, reset to that previous commit, and try again. As you can see (and what has happened in the past), there can easily be a system-breaking bug that appears and I don't fix it before someone clicks update. In the case of the update system being broken, then the user has little alternative to reinstalling, unless they can navigate the command line or can wait for a response to a github issue they create.

**Comment by kizniche** [comment]
With regard to upgrading the database, I make sure both the upgrade and downgrade commands work as expected, creating/deleting/editing the appropriate tables/columns.

**Pull request merged**
