### PR TITLE
99% whitespace.  After lining up the large (sometimes very large) if …

### PR DESCRIPTION
**Pull request by Cabalist**
…conditionals I got rid of some redundant parentheses as well.    I want to tackle the IF statements next.

I understand the code better now.  I hope to have some commits soon that will improve the code duplication.

### CODE REVIEW

**Comment by kizniche** [comment]
What are the whitespace edits?... github won't show the edits because there are so many.

**Comment by kizniche** [comment]
Ah, I see! (after comparison analysis in text editor)

**Comment by kizniche** [comment]
Thanks, again, for all the help. This is my first Python project. It may be an ugly baby, but it'll grow up strong and well-nourished with the open-source community. :)

**Comment by Cabalist** [comment]
I've been watching your project for awhile.  I really like it!  I'll contribute when I can.  :)

**Pull request merged**
