### PR TITLE
Dev 5.0

### PR DESCRIPTION
**Pull request by etiology**
Initial start on fixing testing and some minor clean up.

  - Moved the ```db``` and ```influx_db``` instance into a module called extensions because they are both flask extensions.  The application can reference these which will inherit the flask context and configuration when application factory runs.
  - Updated the hardware specific imports to mock for running tests.  Now the software tests can be ran on any hardware or platform

### CODE REVIEW

**Comment by kizniche** [comment]
This is the error I'm getting after this merge:

```
Traceback (most recent call last):
  File "./mycodo/start_flask_ui.py", line 11, in <module>
    app = create_app()  # required by the wsgi config and main()
  File "/home/kiz/Mycodo/mycodo/mycodo_flask/app.py", line 59, in create_app
    register_extensions(app)
  File "/home/kiz/Mycodo/mycodo/mycodo_flask/app.py", line 89, in register_extensions
    misc = Misc.query.first()
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 500, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/scoping.py", line 78, in __call__
    return self.registry()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/_collections.py", line 990, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 771, in create_session
    return SignallingSession(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 153, in __init__
    self.app = app = db.get_app()
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 922, in get_app
    raise RuntimeError('application not registered on db '
RuntimeError: application not registered on db instance and no application bound to current context
```

**Comment by etiology** [comment]
my bad let me fix it.

**Comment by etiology** [comment]
Ok this will take some time.  I've gotten the testing suite back up and switch it to using the alchemy version of factory boy but there are some strange import knots happening here.  I keep getting the following error and you can ignore the class it talks about because it fails on which ever model it sees first:
```InvalidRequestError: Table 'alembic_version' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.```

There is something in flaskutils that appears to be defining tables multiple times based on the way the imports are working.  The [inject_mycodo_version](https://github.com/kizniche/Mycodo/blob/622dc4af54c873aeacdfb4b35f802dc0e5c56dca/mycodo/mycodo_flask/general_routes.py#L566-L584) appears to implicated in this but it may just be the import that gets the interpreter to look at the flaskutils module which contains the offending code.

I need some time to think on it.

**Comment by kizniche** [comment]
Okay. Thanks for the help. I'll hold off on any major commits and if I want to modify the dev-5.0 I'll just create a new branch for now.

**Comment by kizniche** [comment]
If I wanted to add to the [last working commit](https://github.com/kizniche/Mycodo/tree/c3d9671d546816168de3bdd5f1e2069c4f0ce3fe), what would be the best approach to do that? Branch at that commit into a new dev-5.0-feature branch, then merge back at a later time after your commits have been merged? I don't want to do anything that makes it more difficult later on.

**Comment by etiology** [comment]
I'm concerned that I might not have enough time to complete what I started.  I can always do a pull and integrate any changes. So I would advise moving forward without my code and I'll catch up when I can

**Comment by kizniche** [comment]
I kind of went a little crazy yesterday with a few cups of coffee and fixed the entire broken Methods functionality (frontend and backend) to use the new two-table database. I'm sure the code can be made more efficient (for instance, I haven't implemented using foreign keys yet, but they're there for when I do), but at least it seems everything is working in dev-5.0.

I'm going to wait a little while longer before releasing 5.0 to mull over the database structure to see if there's anything I can do to make it better. I just know that there's going to be something I want to modify once it's released and I'll then be locked into using that structure if I can't use alembic to modify it (sqlite3 doesn't support some actions that sql does).

Would you say continuing to use sqlite3 is a wise choice? My main reasons for choosing that were 1. inexperience with databases, and 2. convenience of the entire database in one file.

**Comment by kizniche** [comment]
I've been trying without success to get past this error in the testing:

```OperationalError: (sqlite3.OperationalError) no such table: users```

The database creation test works, but none other. You mentioned you got everything working, except something causing an issue. Could you perhaps commit to a new branch so I can see what you did?

>  I've gotten the testing suite back up and switch it to using the alchemy version of factory boy

Is it possible to disable what is causing the latest error that was stopping you, then at a later time come back and figure out what that issue is?

I'm eager to get testing working again, but I also don't want to bother you too much. If you could push the last edits you made, so I could study them, that may help me enough to figure it out.

**Comment by etiology** [comment]
I'll see if I can get some time today or tomorrow to tackle it.

**Comment by kizniche** [comment]
Thanks! It's very appreciated.

**Comment by etiology** [comment]
@kizniche I got [something started](https://github.com/etiology/Mycodo/tree/get_tests_working) if you want to take a look at it.

This has working tests for creating database models, viewing endpoints, and a few model factories using the faker module for random info creation.

**Comment by kizniche** [comment]
Wow, that's great! I've been going over the changes, merging them with the dev-5.0 branch, which I [committed](https://github.com/kizniche/Mycodo/commit/a43cde963d97735f53a782876aefd0a3f38ad89e).

I found that for some strange reason, your pull didn't get all the most recent code, so I had to update a bunch of the database schema. But I now have the daemon and frontend working with my current database file.

Next, on to testing. I have about half the tests failing, with errors such as this (excerpt):

```
--------------------------------------------------------------------------------
ERROR in __init__ [/home/kiz/Mycodo/mycodo/databases/__init__.py:24]:
Failed to save <mycodo.databases.models.role.Role object at 0x6f3b93b0> due to error: (sqlite3.IntegrityError) UNIQUE constraint failed: roles.id [SQL: u'INSERT INTO roles (id, name, edit_settings, edit_controllers, edit_users, view_settings, view_camera, view_stats, view_logs) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (1, 'Admin', 1, 1, 1, 1, 1, 1, 1)]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
ERROR in __init__ [/home/kiz/Mycodo/mycodo/databases/__init__.py:24]:
Failed to save <mycodo.databases.models.role.Role object at 0x6f3b93b0> due to error: (sqlite3.IntegrityError) UNIQUE constraint failed: roles.id [SQL: u'INSERT INTO roles (id, name, edit_settings, edit_controllers, edit_users, view_settings, view_camera, view_stats, view_logs) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (2, 'Editor', 1, 1, 0, 1, 1, 1, 1)]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
ERROR in __init__ [/home/kiz/Mycodo/mycodo/databases/__init__.py:24]:
Failed to save <mycodo.databases.models.role.Role object at 0x6f3e11f0> due to error: (sqlite3.IntegrityError) UNIQUE constraint failed: roles.id [SQL: u'INSERT INTO roles (id, name, edit_settings, edit_controllers, edit_users, view_settings, view_camera, view_stats, view_logs) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (3, 'Monitor', 0, 0, 0, 1, 1, 1, 1)]
--------------------------------------------------------------------------------
```

Also this error: ```fixture 'testapp_no_admin_user' not found``` and I see there's an unresolved reference to ```login_user``` in ```test_endpoints.py```

I'll continue to see if I can figure these things out, but just wanted to thank you and let you know what happened on my end after the merge.

**Comment by kizniche** [comment]
I'm fairly sure I didn't mess any of your work up. I cloned your repo, changed to your branch, then replaced my working Mycodo install (dev-5.0 branch) with yours, then synchronized all the new filed, deleted the old, then fixed the database schema, then committed. So, that should have all your edits incorporated correctly.

**Comment by etiology** [comment]
Those errors are most likely coming from the [populate_db call](https://github.com/kizniche/Mycodo/blob/a43cde963d97735f53a782876aefd0a3f38ad89e/mycodo/databases/models/__init__.py#L92-L103).   

```python
def populate_db(*args, **kwargs):
    """
    Populates the db tables with default values.  This will likely
    be replaced in the future by just setting the default values in the
    db fields
    """
    [Role(**each_role).save() for each_role in USER_ROLES]

    AlembicVersion().save()
    DisplayOrder(id=1).save()
    Misc(id=1).save()
    SMTP(id=1).save()
```

The ```USER_ROLES``` defined in mycodo.config

```python
# User Roles
USER_ROLES = [
    dict(id=1, name='Admin',
         edit_settings=True, edit_controllers=True, edit_users=True,
         view_settings=True, view_camera=True, view_stats=True,
         view_logs=True),
    dict(id=2, name='Editor',
         edit_settings=True, edit_controllers=True, edit_users=False,
         view_settings=True, view_camera=True, view_stats=True,
         view_logs=True),
    dict(id=3, name='Monitor',
         edit_settings=False, edit_controllers=False, edit_users=False,
         view_settings=True, view_camera=True, view_stats=True,
         view_logs=True),
    dict(id=4, name='Guest',
         edit_settings=False, edit_controllers=False, edit_users=False,
         view_settings=False, view_camera=False, view_stats=False,
         view_logs=False)
]
```

It would be nice to have an **INSERT OR IGNORE** behavior there.   Maybe an ```INSERT OR REPLACE``` or something.  You could always change the ```populate_db()``` function do a query on roles first and ignore the known configs:
```python
# check for previously defined roles and either make new ones or skip
previous_roles = {role.name: role.id for role in Roles.query.all()}  # dict('Admin'=1, 'Editor'=2, ...)
 [Role(**role_cfg).save() for role_cfg in USER_ROLES if role_cfg['name'] not in previous_roles]
```

or if you want to updates to be able to modify the current db roles you could do something like the ```INSERT OR REPLACE``` option:
 ```python
def populate_db():
    """ Adds required configurations to the database tables """
    known_roles = {r.name: r for r in Roles.query.all()}
    for role_cfg in USER_ROLES:
        if role_cfg.name in known_roles:
            # Update Previous Roles
            previous_record = known_roles[role_cfg.name]
            for k, v in role_cfg.items():
                if k == 'id':                   # skip the primary key
                    continue
                setattr(previous_record, k, v)  # set values from app config
                previous_record.save()
        else:
            # Create new roles
            Role(**role_cfg).save()             
            
```

**Comment by etiology** [comment]
About the test work.  Don't worry about making changes or anything.  Feel free to cherry-pick the stuff in there if you find it helpful.  You noticed the ```mycodo_db``` fixture is gone since it's no longer needed which means that the remaining tests that have it in their signatures will need to be updated.  I didn't finish refactoring all of the tests but the the initial [login redirect check](https://github.com/etiology/Mycodo/blob/0487ecaa9c9334ee8a51ba6fc98dc6ba143017ec/mycodo/tests/software_tests/test_mycodo_flask/test_endpoints.py#L20-L67) runs.  

Also you'll want to remove the ``` Mycodo/mycodo/tests/software_tests/test_mycodo_flask/conftest``` file because it's over writing the  Mycodo/mycodo/tests/software_tests/conftest``` fixtures

**Comment by kizniche** [comment]
Ah, that makes sense. I now have the fixture tests working and ```test_routes_when_not_logged_in```. I had to add [redirects_to_admin_creation_page](https://github.com/kizniche/Mycodo/blob/119d1910cd059754b29fe3db845d68768e3cfd7e/mycodo/tests/software_tests/test_mycodo_flask/test_endpoints.py#L20-L24) for it to work because without an admin user, the login page won't be displayed, rather the admin creation page. Also getting these errors with that test:

```
--------------------------------------------------------------------------------
ERROR in __init__ [/home/kiz/Mycodo/mycodo/databases/__init__.py:24]:
Failed to save <User: <name='Daniel Edwards', email='elizabeth61@herman-hays.info' is_admin='False'> due to error: (sqlite3.IntegrityError) UNIQUE constraint failed: users.name [SQL: u'INSERT INTO users (name, password_hash, email, role, theme) VALUES (?, ?, ?, ?, ?)'] [parameters: (u'Daniel Edwards', '$2b$12$59dLDID1yD2HpZvqJ575EeH52tnXDvQnSK207S9gYl6gAdU3cl3d.', u'elizabeth61@herman-hays.info', None, None)]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
ERROR in __init__ [/home/kiz/Mycodo/mycodo/databases/__init__.py:24]:
Failed to save <User: <name='Daniel Edwards', email='elizabeth61@herman-hays.info' is_admin='False'> due to error: (sqlite3.IntegrityError) UNIQUE constraint failed: users.name [SQL: u'INSERT INTO users (name, password_hash, email, role, theme) VALUES (?, ?, ?, ?, ?)'] [parameters: (u'Daniel Edwards', '$2b$12$59dLDID1yD2HpZvqJ575EeH52tnXDvQnSK207S9gYl6gAdU3cl3d.', u'elizabeth61@herman-hays.info', None, None)]
--------------------------------------------------------------------------------
```

**Comment by kizniche** [comment]
New [commit](https://github.com/kizniche/Mycodo/commit/7ec5c9924199ee1e2cb2a90050aef4c9609a2823). I modified ```test_sees_admin_creation_form``` to work, considering that is what ```test_routes_when_not_logged_in``` was doing because there wasn't an admin user in the database. ```test_routes_when_not_logged_in``` is now failing because I haven't figured out how to remove ```mycodo_db``` properly and get admin user creation and login working for the endpoint tests to work properly.

**Comment by kizniche** [comment]
After studying ```test_routes_when_not_logged_in``` a little more, I see ```testapp``` is using ```create_admin_user``` to create an admin user, however this is still redirecting to the create admin page afterward, for some reason. Just talking aloud here :)

**Comment by kizniche** [comment]
Ah, I fixed it by renaming a stray ```user_role``` to ```role```. Now the admin creation works. Progress... Slow but rewarding.

**Comment by kizniche** [comment]
I managed to get all endpoint tests working except the sensor addition. I also fixed a few issues with the travis-ci environment with the .travis.yml file, and I'm glad to say the little build icon is now glowing green!

**Pull request merged**
