### PR TITLE
Welcome message database statement comparison

### PR DESCRIPTION
**Pull request by boomstick8x**
Just add comparison to hide zero from welcome page if message is not already set in db.

### CODE REVIEW

**Comment by kizniche** [comment]
Hmmm. When would $login_message be '0'?

**Comment by kizniche** [comment]
And if so, wouldn't it be: `if ($login_message != '' && $login_message != '0')` ?

**Comment by kizniche** [comment]
In update-database.py, it creates the new column with:
`AddColumn(sql_database_mycodo, 'Misc', 'Login_Message', 'TEXT')`

This makes it a NULL value, which this command will change it to '':
`ModNullValue(sql_database_mycodo, 'Misc', 'Login_Message', '')`

So, in theory, the database update would create the column and then change the NULL value to ''

**Comment by kizniche** [comment]
I believe just comparing if ('0') would always be true, because the character '0', not the number 0, is a number other than 0, and anything other than FALSE and 0, is true.

**Comment by boomstick8x** [comment]
It put 0 in my db and because of that I saw zero on login page.
Maybe it sqllite feature?

**Comment by boomstick8x** [comment]
I got it on fresh created database. Or maybe the right solution will be `!==`!

**Comment by boomstick8x** [comment]
What do you think about this?
https://www.sqlite.org/nulls.html

**Comment by boomstick8x** [comment]
http://stackoverflow.com/questions/25686226/android-sqlite-fts3-what-should-i-insert-null-values-or-empty-strings

**Comment by kizniche** [comment]
Okay. I think I know what happened...

I initially created the database update to change the NULL value to 0. Then I edited that to be `''`

You must have updated between these updates to get the `'0'` and not `''`

I chose to use `''` instead of NULL because when the textarea is left blank and saved from the Settings tab, it saves that as `''` and I wanted this to be the default value, otherwise I would have to put a conditional for both NULL and `''`

**Comment by boomstick8x** [comment]
Just now pulled up with git to newer version 3.5.77 (git log commit 412dc2a), delete `mycodo.db` and `users.db`,  create new db with `sudo /var/www/mycodo/update-database.py -i` and zero already on login page.
p.s. Will test further

**Comment by kizniche** [comment]
That's unexpected. Let me know what you find. I might not get to test until Sunday night or Monday. I'm leading a group to camp in the Great Smokey Mountains this weekend.

**Comment by kizniche** [comment]
I just figured it out. I edited the wrong value when I added Login_Message. I had forgotten each Table that's created has a Unique column named Id, and that is the true first column.

`cur.execute("INSERT OR IGNORE INTO Misc VALUES('0', '', 0, 300, 1, 15)")`

should have been:

`cur.execute("INSERT OR IGNORE INTO Misc VALUES('0', 0, '', 300, 1, 15)")`

I just pushed an update that should make Login_Message default to `''`

**Comment by kizniche** [comment]
I haven't tested it but if you want to confirm it works, I'll close this pull request ;)

**Comment by boomstick8x** [comment]
Ok! And sorry for disturbance, I just always want to try my first pull request here(sorry for choosing your project for that) and hurrying while investigating what`s going on.
And give me 10 minutest for test.

**Comment by kizniche** [comment]
It's perfectly fine. You helped uncover a bug. That's progress to me. There's a lot of code. I'm sure there will be more bugs to fix.

**Comment by boomstick8x** [comment]
Yep, all right now!

**Comment by boomstick8x** [comment]
p.s. Are you using something similar phpmyadmin to look into database files of sqlite?

**Comment by kizniche** [comment]
It was actually 2 bugs that were fixed! Thanks for the help and testing.

I use the web interface "Mycodo Database" button on the Data tab most of the time to view the database. I haven't really had a need yet to manually edit the database. By only using Mycodo to do it, I am reasonably assured everything works (if it doesn't work, I copy a backed up database and try again).

**Comment by boomstick8x** [comment]
I have not close look in the Data tab before, will look further.
p.s. Have a nice weekend!

**Comment by kizniche** [comment]
Thanks. You, too.

Until the next update.

**Pull request closed without merging**
