### PR TITLE
Fix Grove LCD RGB Backlight

### PR DESCRIPTION
**Pull request by rbultman**
- Gets rid of the dependency on the Grove python library
- Wires up the actions for the backlight color changes

### CODE REVIEW

**Comment by kizniche** [comment]
I see you're using an lcd table column location_backlight, but that column doesn't exist. Perhaps we just hard code this into the grove lcd module rather than setting a database column? Since it's the only one, hard coding it shouldn't be an issue, and if any more RGB lcds are added in the future, we can create a database upgrade script to allow configuring the address.

**Comment by kizniche** [comment]
Ah, I see it is hard coded with the DB entry commented out. Everything looks good, but I think the missing DB column will cause an error. I'll take a closer look later. Thanks for the PR!

**Comment by rbultman** [comment]
> I see you're using an lcd table column location_backlight, but that column doesn't exist. Perhaps we just hard code this into the grove lcd module rather than setting a database column? Since it's the only one, hard coding it shouldn't be an issue, and if any more RGB lcds are added in the future, we can create a database upgrade script to add a database column.

I was unable to figure out how to get that to work.  I do think it should be configurable by the user, but I'm not sure how the addresses are set on the LCD modules.

**Comment by rbultman** [comment]
> Ah, I see it is hard coded with the DB entry commented out. Everything looks good, but I think the missing DB column will cause an error. I'll take a closer look later. Thanks for the PR!

Yes, it's hard coded.  I didn't experience an error in testing, but I probably didn't test everything.  

I learned a lot about the system with this change, but the DB concept is a little bit outside of my current understanding.

**Comment by kizniche** [comment]
>I didn't experience an error in testing

I believe "new_lcd.location_backlight = '0x62'" should cause a column not found error. I'm merging because everything else looks good. I'll see about adding a location_backlight column to the database and add that as an LCD option.

**Comment by kizniche** [comment]
FYI, in order to create a new upgrade script in Mycodo/databases/alembic/versions:

```bash
cd Mycodo/databases
../env/bin/alembic revision -m "Add location_backlight column to lcd"
```

This new version script can then be formatted similarly to the others. Additionally, after Mycodo updates the database, Mycodo/databases/alembic_post.py is executed to run any extra python script that couldn't be executed in the upgrade script. This only occurs for the particular version upgrade if the code that's commented out in the upgrade function is uncommented and allowed to run, which adds that particular version string to a list to be executed. That's a lot to explain, and I'm sure it's a bit confusing, but I figured if I start explaining the upgrade system, I should go all the way.

**Comment by kizniche** [comment]
I typically create a backup and then test if the script works:

```bash
cd Mycodo/databases
cp mycodo.db mycodo.db.bu
../env/bin/alembic upgrade head
```

And if it didn't work, I edit the script, and try again, and repeat until it works:

```bash
cp mycodo.db.bu mycodo.db
../env/bin/alembic upgrade head
```

**Comment by kizniche** [comment]
I just pushed 16f95461d585efa36177b6cbd0d70dde8bdffa0c that contains all the changes for adding the database column upgrade script and web form.

**Comment by rbultman** [comment]
Thanks for that detail.  This is a pretty awesome system you have put together.  I'm enjoying working with it.

**Pull request merged**
