### PR TITLE
codacy_grade_improvement_raspi_sensor

### LINKED ISSUE #145: Almost every sensor implement a different read() return value
All of the sensors appear to have a ```read()``` method and ```stopSensor()``` (incorrect camel case name), but with respect to the ```read()``` method they return different values.  Some return ```None``` others return ```str```, or ```int``` values, and others return either an ```int``` or ```None```.

This needs to be standardized.  We could use a parent class to ensure that these methods are present and overwritten in each sensor but we need some guides on what the return values should be.

### PR DESCRIPTION
**Pull request by etiology**
closes #145

First rework of the sensor classes starting with the RaspberryPiCPUTemp and RaspberryPiGPUTemp classes.  Created AbstractSensor Class to enforce consistancy and provide a place to document the Sensor class methods.

### CODE REVIEW

**Comment by etiology** [comment]
This codacy failure is strange.  I have tests that verify that these functions are returning an iterator.  

The specific failure is based on the the ```__iter__``` return.  The object returned must be an iterator which means that it implements both the ```__iter__``` special method and ```next```, which our class does. 
```python
def  __iter__(self):
        """ Support the iterator protocol """
        return self

def next():
        """ Get next temperature reading """
        if self.read():  # raised an error
            raise StopIteration  # required
        return dict(temperature=float('{0:.2f}'.format(self._temperature)))
```

**Comment by etiology** [comment]
It looks like it may have to do with python 3 compatibility.  Codacy is using pylint to run this check and [here is the pylint update to implement the ```__iter__``` check](https://bitbucket.org/logilab/pylint/pull-requests/48/add-new-warning-for-non-iterators-returned/diff).  The tests provided is for python 3 .

Actually I think the issue is in these tests (again pylint).  Specifically the ThirdBadIterator:
```python
"""Check non-iterators returned by __iter__ """

# pylint: disable=too-few-public-methods

__revision__ = 0

class FirstGoodIterator(object):
    """ yields in iterator. """

    def __iter__(self):
        for index in range(10):
            yield index

class SecondGoodIterator(object):
    """ __iter__ and next """

    def __iter__(self):
        return self

    def __next__(self): # pylint: disable=no-self-use
        """ Infinite iterator, but still an iterator """
        return 1

class ThirdGoodIterator(object):
    """ Returns other iterator, not the current instance """

    def __iter__(self):
        return SecondGoodIterator()

class FourthGoodIterator(object):
    """ __iter__ returns iter(...) """

    def __iter__(self):
        return iter(range(10))

class FirstBadIterator(object):
    """ __iter__ returns a list """

    def __iter__(self):
        return []

class SecondBadIterator(object):
    """ __iter__ without next """

    def __iter__(self):
        return self

class ThirdBadIterator(object):
    """ __iter__ returns an instance of another non-iterator """

    def __iter__(self):
        return SecondBadIterator()
```

**Comment by kizniche** [comment]
Hmm. So we should just ignore the issues for now?

I merged the pull, but I'm actually on the road for the next 1 to 2 days to an area without cell/4g service. I'll review everything deeper when I get back.

**Comment by etiology** [comment]
I got confirmation from codacy this morning that the pylint tests **do** run in python 3.  So we should be aware of some of the errors that occur for 2/3 compatibility.

**Comment by kizniche** [comment]
I'm currently updating all sensor classes according to your model here. I realize there will need to be specific tests for certain sensors, but can we have certain tests run for conserved functionality in every sensor?

Also, I'm having two tests fail for the raspi.py sensor:

```
=================================== FAILURES ===================================
_______________ test_raspberry_pi_cpu_temp_raises_stop_iteration _______________

    def test_raspberry_pi_cpu_temp_raises_stop_iteration():
        """ stops iteration on read() error """
        with pytest.raises(StopIteration):
>           RaspberryPiCPUTemp().next()
E           Failed: DID NOT RAISE <type 'exceptions.StopIteration'>

test_raspi_sensor.py:136: Failed
_______________ test_raspberry_pi_gpu_temp_raises_stop_iteration _______________

    def test_raspberry_pi_gpu_temp_raises_stop_iteration():
        """ stops iteration on read() error """
        with pytest.raises(StopIteration):
>           RaspberryPiGPUTemp().next()
E           Failed: DID NOT RAISE <type 'exceptions.StopIteration'>

test_raspi_sensor.py:264: Failed
=========================== 2 failed in 1.08 seconds ===========================

Process finished with exit code 0
```

**Comment by etiology** [comment]
We may need to mock the open statement in that read() to raise an exception. I ran the tests on a system that was obligated to fail because the read method couldn't possibly succeed. You must be running the tests on a system where it could actually work. 

So we should mock that read methods internals to raise an exception. That's my bad. I should have forced the condition of a failure on that.

**Comment by etiology** [comment]
wait. I might need to be in front of my computer to look into this. This test doesn't smell right.

**Comment by etiology** [comment]
Also I was thinking that the AbstractSensor class could implement the python 3 version of next and just call the python 2 version. It should make it pass the pylint test and get it ready for python 3

**Comment by etiology** [comment]
>can we have certain tests run for conserved functionality across sensors?

I think that's a good goal to move towards. I was hoping that there was a way but I haven't gone through each sensor implementation yet. I think many of the tests can be repeated but obviously some will be sensor specific.

**Comment by etiology** [comment]
Ok.  So now that I'm thinking about what the behavior should be I have some comments on this.  I want to focus on the ```StopIteration ``` exception.  [```StopIteration``` is required for iterators](https://www.python.org/dev/peps/pep-0234/) and should be raised when ```next()``` or ```__next__``` is exhausted. 

Now that I'm looking at the code I see two places where this is raised but first look at the [```next()```](https://github.com/kizniche/Mycodo/blob/34de420eb465f01a0af2573aeb5cfcc9129be7d0/mycodo/sensors/raspi.py#L85-L89) method:
```python
    def next(self):
        """ Get next temperature reading """
        if self.read():  # raised an error
            raise StopIteration  # required
        return dict(temperature=float('{0:.2f}'.format(self._temperature)))
```

This looks right to me since ```next()``` needs to raise the exception.  However I have it raised in the read() method too:
```python
        try:
            self._temperature = self.get_measurement()
            return  # success - no errors
        except StopIteration:
            # expected behavior in tests.  Typically there is a finite list of measurements in a list so we re-raise
            raise StopIteration
```

It could just return 1 instead of raising.  Perhaps that would be better.  Basically right now ```read()``` raises and it propagates through up to the ```next()``` method but the ```if self.read(): ``` part never actually gets a chance to raise.  

We could get rid of the ```except StopIteration``` catch in the ```read``` method and not afect anything since at the end of the exceptions it returns ```1```

**Comment by kizniche** [comment]
That sounds reasonable. I'm minutes away from pushing a bunch of sensor module changes. Should I remove those three lines in all the read()s?

**Comment by etiology** [comment]
Now about the failure to raise:
```
=================================== FAILURES ===================================
_______________ test_raspberry_pi_cpu_temp_raises_stop_iteration _______________

    def test_raspberry_pi_cpu_temp_raises_stop_iteration():
        """ stops iteration on read() error """
        with pytest.raises(StopIteration):
>           RaspberryPiCPUTemp().next()
E           Failed: DID NOT RAISE <type 'exceptions.StopIteration'>
```

We should generate an error coming from the ```self.get_measurement()``` call:
```python
def test_raspberry_pi_gpu_temp_raises_stop_iteration():
    """ stops iteration on read() error """
    with mock.patch('mycodo.sensors.raspi.RaspberryPiGPUTemp.get_measurement', side_effect=IOError):
        with pytest.raises(StopIteration):
            RaspberryPiGPUTemp().next()
```

Here I'm having ```get_measurement()``` throw an ```IOError```

**Comment by kizniche** [comment]
Hmm. Some of the sensors I've taken out the IOError because it's not pertinent to the sensor. Could we use the Exception instead or does it have to be specifically IOError?

**Comment by etiology** [comment]
>Should I remove those three lines in all the read()s?

Yeah that should be ok.  Can you add the ```__next__()``` method to the ```AbstractSensor``` class and see if that passes codacy's pylint test?  It needs to basically call ```next()```.  No point in repeating any code.

```python
def __next__(self):
    return self.next()
```

I think that should work.

**Comment by etiology** [comment]
You can use whatever exception you want.  For all tests you might just trying raising ```Exception``` instead of anything specific.

**Comment by etiology** [comment]
Might need another test to ensure that after catching an ```Exception``` we still return ```1``` from the ```read()```.
```python
def test_raspberry_pi_gpu_temp_read_returns_1_on_exception():
    """ Verify the read() method returns true on error """
    with mock.patch('mycodo.sensors.raspi.RaspberryPiGPUTemp.get_measurement', side_effect=Exception):
            assert RaspberryPiGPUTemp().read()
```

**Comment by kizniche** [comment]
Here's the result of running the tests with the 2 altered and 2 new tests included:

```
ssh://kiz@192.168.0.7:22/usr/bin/python -u /home/kiz/.pycharm_helpers/pycharm/pytestrunner.py -p pytest_teamcity /home/kiz/Mycodo/mycodo/tests/software_tests/test_sensors
Testing started at 19:22 ...
============================= test session starts ==============================
platform linux2 -- Python 2.7.9, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: /home/kiz/Mycodo/mycodo/tests/software_tests/test_sensors, inifile: 
collected 31 items 

test_raspi_sensor.py ............ERROR:root:CPU temperature reading returned IOError: 
.ERROR:root:Unknown error in RaspberryPiCPUTemp.get_measurement(): 
............ERROR:root:RaspberryPiGPUTemp.get_measurement() method raised IOError: 
.ERROR:root:Unknown error in RaspberryPiGPUTemp.get_measurement(): 
.....

========================== 31 passed in 0.97 seconds ===========================

Process finished with exit code 0
```

**Comment by etiology** [comment]
That's great.  I can also see the logging statements getting called from the ```except Exception as e:``` sections

**Comment by kizniche** [comment]
Just pushed the module updates in commit cc9f3fc

**Comment by kizniche** [comment]
Oh, damn, I just saw you've been making a bunch of edits on your dev branch. Did I just interfere with those edits with my last commit? 😦

**Comment by etiology** [comment]
Don't think so.  It should be fine.

Anything in my dev branch is not important.  I have other branches where I'm working on things.  Many of those aren't pushed anywhere yet.

**Pull request merged**
