### PR TITLE
Add Grove RGB LCD

### PR DESCRIPTION
**Pull request by rbultman**
This PR adds the Grove LCD RGB Backlight as a device.
https://wiki.seeedstudio.com/Grove-LCD_RGB_Backlight/

### CODE REVIEW

**Comment by kizniche** [comment]
Nice addition, thank you!

**Comment by kizniche** [comment]
I think adding a Function Action to change the backlight color would be a nice feature. This would allow things like turning red when temperature is too hot, for instance.

**Comment by kizniche** [comment]
How is the library installed? I don't see the dependency listed in config.py and I'm having a difficult time finding the official library.

**Comment by kizniche** [comment]
I believe this is what I'm looking for: https://github.com/DexterInd/GrovePi/blob/master/Software/Python/grove_rgb_lcd/grove_rgb_lcd.py

However, https://github.com/DexterInd/GrovePi instructs to use this command to install:

```
curl -kL dexterindustries.com/update_grovepi | bash
```

Which also installs a lot of other stuff (totaling 25 MB). Do you know if a way to install just the LCD library without the rest (without copying the class into Mycodo)?

**Comment by rbultman** [comment]
Whoops!  I can see I have other things not implemented too.  I should have not have made that PR.  Yes, that is the repo for that library.  Let me try to figure this out.  I'm fairly new to python.  Let me see if I can figure that out.

I'll add that function action too - good idea.

**Comment by kizniche** [comment]
I just made a bunch of edits, including adding a Function Action to change the LCD color. Let me push those before you make any changes.

**Comment by kizniche** [comment]
If there's no easy way to install just the grove LCD library, we can just copy the grove_rgb_lcd.py functions into the Mycodo lcd module file.

**Comment by rbultman** [comment]
It doesn't look like there is an easy way to do that.  I'll take care of doing the copying tomorrow, testing, and submitting another PR.

**Pull request merged**
