### PR TITLE
3d array

### PR DESCRIPTION
**Pull request by Cabalist**

### CODE REVIEW

**Comment by kizniche** [comment]
@Cabalist 
Strange, with PHP <5.5, no error. With PHP >5.5, I get:
TypeError: any() takes exactly one argument (20 given)

**Comment by kizniche** [comment]
Er..  I meant diff versions Python...

**Comment by kizniche** [comment]
Actually. My mistake for both of those.. Both Python 2.7.9 and are giving the same error.

**Comment by kizniche** [comment]
Found the solution: any(1, 2, 3) should be any((1, 2, 3))

**Comment by Cabalist** [comment]
Yep!  My bad  I just caught that as well.

**Comment by kizniche** [comment]
Does any((1, 2, 3)) differ from any([1, 2, 3])?

**Comment by Cabalist** [comment]
Nope.  (1,2,3) is a tuple and [1,2,3] is a list.  Any is expecting one
argument that is an iterable.  They are both iterables so we are good.

**Pull request merged**
