### PR TITLE
saving upgrade_commands.sh changes

### PR DESCRIPTION
**Pull request by ZiqueYuutaka**
Fixed pigpio installation and removal bash script to reflect changes by pigpio author. New installation instructions found here:
http://abyz.me.uk/rpi/pigpio/download.html

Left code commented for comparison and feedback.

### CODE REVIEW

**Comment by kizniche** [comment]
This kind of change would cause issues if a breaking change were to be pushed to the pigpio master branch. By specifying a specific release that has been tested to work, we can ensure users have a consistent;y successful install. Rather than install from master, why not just change the current version (v77) to the latest release (v79)?

**Comment by ZiqueYuutaka** [comment]
Makes sense. Making the necessary changes and will be pushing that up asap. Thanks!

**Comment by kizniche** [comment]
I just noticed that it's saving the file via wget as pigpio.tar.gz however it's attempting to remove pigpio-latest.tar.gz which is an incorrect filename. This issue existed prior to your PR, but can you make that change to correct my error? Once that's done, it will look good to merge. Thanks.

**Comment by kizniche** [comment]
Nice! Thanks.

**Pull request merged**
