### PR TITLE
Optimize timelapse and still retrieval

### PR DESCRIPTION
**Pull request by kimbernator**
Resolves https://github.com/kizniche/Mycodo/issues/1086

This records the filename and timestamp of still and timelapse images in the database as they are generated and references that instead of scanning the filesystem for the newest of either. This should reduce load times for the camera administration page as well as dashboards with camera widgets showing recent images, especially when there are many files it would otherwise need to parse through.

`get_camera_image_info` still does a `listdir` on the filesystem for the array of timelapse images which I think could be optimized somehow (probably moved into its own method and called separately), but that's just a single call to list the directory contents whereas the checks for recent stills/timelapses would run a check for the mtime on each file separately which is where the bulk of load time comes from.

### CODE REVIEW

**Comment by kizniche** [comment]
Thanks for the PR. There will need to be an alembic upgrade script made to add the new table columns to existing users' databases. I can do this or you can. There are a number of examples that can be found in https://github.com/kizniche/Mycodo/tree/master/databases/alembic/versions

**Comment by kizniche** [comment]
You can generate a new script template automatically by running

```bash
cd Mycodo/databases && ../env/bin/alembic revision -m "description of database change"
```

and it will be created in the versions directory.

**Comment by kimbernator** [comment]
I figured there would need to be a migration somewhere, thanks for the heads up. I just pushed another commit with the migration file.

**Comment by kizniche** [comment]
Can you confirm this works for both the camera page and the camera widget?

**Comment by kimbernator** [comment]
A few bugs needed ironing out, just took me a minute to get it tested. Both the camera page and widget work as expected.

**Comment by kimbernator** [comment]
Anything else you need from me to get this merged?

**Comment by kizniche** [comment]
No, sorry. I haven't had time to thoroughly test this. It will likely be included in the next release, though, unless there's a major bug that needs an immediate bugfix release. I'll try to get to testing this this weekend or sooner.

**Comment by kizniche** [comment]
This pull request has been mentioned on **DIY Automation Forum**. There might be relevant details there:

https://forum.kylegabriel.com/t/data-overlay-on-camera-image-from-inputs-and-outputs/406/2

**Pull request merged**
