### PR TITLE
Added new input, output, and function for Grove Pi+

### PR DESCRIPTION
**Pull request by rbultman**
This PR exposes the DHT11/DHT22 sensor and the multi-channel relay I2C board from Seeed Studio via the Grove Pi+ hat.  It also adds a bang-bang/hysteretic function for simple control of an output from an input, attempting to maintain the input level at a setpoint with hysteresis.

Note that this requires that the [Grove Pi+ repo from Dexter Industries](https://github.com/DexterInd/GrovePi) be set up manually.

Grove Pi+: https://www.seeedstudio.com/GrovePi.html
DHT11: https://wiki.seeedstudio.com/Grove-TemperatureAndHumidity_Sensor/
DHT22: https://wiki.seeedstudio.com/Grove-Temperature_and_Humidity_Sensor_Pro/
Relay Board, 4 channel:  https://www.seeedstudio.com/Grove-4-Channel-SPDT-Relay-p-3119.html

### CODE REVIEW

**Comment by kizniche** [comment]
Thanks for the PR!

**Comment by kizniche** [comment]
What is the purpose of ```sys.path.insert(1, '/usr/local/bin')``` in grove_temp_humidity.py?

**Comment by rbultman** [comment]
I can probably remove that.  I was confused about how the Dexter GrovePi library gets installed into the system.  I think the files are "known" to python, so I can just do without that.  I'll check that and do another PR if needed.

**Comment by kizniche** [comment]
I have some changes staged for commit. I'll remove it. Thanks for the quick reply.

**Pull request merged**
