### PR TITLE
PR for #1043 : Introducing jmespath for finding values in complex JSON structures

### PR DESCRIPTION
**Pull request by maecki-maecki**
I was lazy and reseted my forked master branch which closed PR#1044 and open a new PR here

### CODE REVIEW

**Comment by kizniche** [comment]
You need to add a dependency in the same format as the paho-mqtt, which is a tuple of 3 values. Also, keep the dependency imports in the same location, in initialize_input().

**Comment by maecki-maecki** [comment]
Like this?

Unnecessary use of a member variable, though since I only need jmespath object statically …

**Comment by kizniche** [comment]
Looks good. I like to keep all the module imports in one place, similarly to how global imports are at the top. It may take an extra variable for this module, but that's not the case for most. For users looking to understand how modules work (e.g. to develop their own), It's nice to have consistency.

**Comment by maecki-maecki** [comment]
Warning: Change might break compatibility for existing configurations when JSON key names contain special characters.
In my case the dash in DS18B20-1 requires to use double quotes for jmespath or it will be interpreted as a numerical minus of two values…

**Comment by kizniche** [comment]
can you include a short description and example of that in the "message" of the module?

**Comment by kizniche** [comment]
It might also be better to horten the option phrase and include all info of how to use the module in the "message".

**Review by kizniche — COMMENTED** [review]
Looks great. Thanks for the update.

**Pull request merged**
