### PR TITLE
tweak: reworked widget title bar on dashboard widgets

### PR DESCRIPTION
**Pull request by gfzdw**
This proposed change removes much of the inline CSS styling on dashboard widgets and centers widget titles within their panels.

I've also knocked down the opacity on the settings cog icon unless the mouse is hovering over the icon or the link is active.

This change has been tested in Chrome, Firefox, Safari, and Opera without displaying any issues at various browser sizes. I also tested all themes to ensure that the change did not break any styling.

Dragging works along with the settings cog link.

I will note that there's still some inline CSS styling being added programmatically via this line:

```python
{% include 'user_templates/{}'.format(file_title_bar) %}
```

For instance, `padding-right` is being added to titles in this function. That inline style is no longer needed. I wasn't able to find the `format` method in the Mycodo codebase, but I did not search too extensively.

## Normal

Mycodo Dashboard - Normal

## Hover over Cog Icon (Settings)

Mycodo Dashboard - Hover

## Smaller Screens

Mycodo Dashboard - Small Screens

## Dark Theme

Mycodo Dashboard - Dark Theme

## Android (Chrome)

Mycodo Dashboard - Android (Chrome)

### CODE REVIEW

**Comment by gfzdw** [comment]
The second commit fixed a small display issue that showed up in darker themes.

**Comment by kizniche** [comment]
Thanks, that looks great.

**Comment by kizniche** [comment]
When testing this, I found Graph title bars don't look great due to buttons (below). How would you fix this so the buttons align to the right? This widget's HTML can be found here:

https://github.com/kizniche/Mycodo/blob/49757297c968c380e4aa723e847b4e8b79166407/mycodo/widgets/widget_graph_synchronous.py#L271-L278

Screenshot_2020-11-13 tango - Default Dashboard Dashboard - Mycodo 8 8 8

**Comment by gfzdw** [comment]
I'll take a look and get back to you shortly. Thanks!

**Comment by gfzdw** [comment]
I'm attempting to fix this, but the changes I make to `Mycodo/mycodo/widgets/widget_graph_synchronous.py` are not rendering in the web browser. I've attempted restarting the frontend and the backend and also restarted the whole machine. I thought it could be related to ``__pycache__``, so I deleted that.

Finally, I thought the templates were possibly being stored in the database, so I moved my database to a backup and reinitialized with a new database.

I still see the same issue. 

```python
    'widget_dashboard_title_bar': """
        <span style="font-size: {{each_widget.font_em_name}}em">{{each_widget.name}}</span>
        <div class="widget-graph-controls">
            {% if widget_options['enable_header_buttons'] -%}
            <button class="btn btn-sm btn-primary" id="updateData{{chart_number}}">Update</button>
            <button class="btn btn-sm btn-primary" id="resetZoom{{chart_number}}">Reset</button>
            <button class="btn btn-sm btn-primary" id="showhidebutton{{chart_number}}">Hide</button>
            {% endif %}
        </div>
    """,
```

As you can see, I'm trying to wrap a DIV around the widget graph controls, but I can't seem to figure out how to test the change.

Is there a higher-level cache or something that I'm missing?

Thanks

**Comment by kizniche** [comment]
Oh, sorry, I forgot to tell you that you need to execute the following:

```
/home/pi/Mycodo/mycodo/scripts/upgrade_commands.sh generate-widget-html
sudo service mycodoflask restart
```

**Comment by gfzdw** [comment]
Thanks. See #881.

**Pull request merged**
