### PR TITLE
Sql cleanup

### PR DESCRIPTION
**Pull request by Cabalist**
More cleaning.  This was semi-automated so their shouldn't be any typos but you should run it on your system to make sure

### CODE REVIEW

**Comment by kizniche** [comment]
I noticed the capitalization of the SQL columns was changed. Will case matter if I already have table columns with capital letter?

**Comment by kizniche** [comment]
Okay, quick test shows it is case-insensitive.

**Comment by kizniche** [comment]
@Cabalist Did you use a script/plugin to format the SQL? I'd like to do the same for my PHP SQL statements for consistency and if there's a tool I'd like to try it instead of doing it all manually.

**Comment by Cabalist** [comment]
I just typed 'SQL pretty' into google.  I see from your most recent links
you most likely did as well.  :)

**Pull request merged**
