### PR TITLE
Changed measure interval for PID regulator.

### PR DESCRIPTION
**Pull request by KnyazSh**
Hi Kyle,

I read a lot about PID control.
 The regulator assumes periodic influence and the period shall be constant. In your implementation the period depends on influence time.
As a result integral component of PID is calculated incorrectly since it considers the previous calculation.

P.S. Your program controls climate in my cabinet with IT equipment. Separate thanks for the program in general!

Best Regards,
Yuriy

### CODE REVIEW

**Comment by kizniche** [comment]
The problem with this update is it will create conflict. For instance,

The interval is 30 seconds, and there is some input and the PID output is 20 seconds on:

With my system, It will activate a relay timer for 20 seconds and the timer to wait to update the PID and (potentially turn the relay on again) will be (interval) + (PID time) = 30 + 20 = 50 seconds.

With your system, it will activate the relay timer for 20 seconds and then activate the wait timer for 30 seconds. When that 30 seconds elapses, it will create a new PID value and potentially try to turn the relay on for another duration while it's already in the middle of the first duration.

**Comment by kizniche** [comment]
How do you propose we overcome this issue?

**Comment by kizniche** [comment]
Well, this is not a critical issue, as there is code implemented that if relay is requested to be on for a new duration, and if the relay is already on, and the new duration is longer than how much time the relay has left to be on, the time the relay has left to be on will be updated to the new duration. So, in theory you could have the Measure Interval be the exact duration between measurement/PID update. This would only mean that the output will not necessarily be how long the relay was turned on for. For instance, if the measure interval is set to 30, the actual relay duration will always be only 30, while the PID output could be 35, 100, 500.

This would play havoc with the relay/power usage chart and the relay graph data. As it stands, the duration of the relay being on is logged at the beginning of the function, when it is turned on. For this to be effective, I would need to move the log writing part to a) the end (if successful completion of the duration) or b) the part where the previous on duration is interrupted if it hasn't run out by the time the new duration is given for that relay. Again, doable.

You also have to take into account that the period can never be truly consistent. If another PID thread is reading the same sensor, the current PID thread will wait in line to read the sensor. Also, there is inherent variability in the time it takes for a successful sensor read. There is code that collects two consecutive measurements and compares them. If they are not similar, it will be reread. This continues for 5 cycles, then exits if it cannot succeed. If there is an aberrant reading or the conditions are changing so rapidly that it cannot get two consistent readings, the period can change dramatically.

What are your thoughts?

**Comment by KnyazSh** [comment]
You wrote responses to the majority of questions). I agree with you.
I assume that will better check a relay status before application and leaves it switched on if it already worked. It is necessary to avoid excess switching of the relay and other equipment.

About the chart of use of a relay/power:
I analyzed yet not all code. I have no time. On it I can't advise now. I hope a little later surely I will make it.

I think it's nothing bad if a period will little change.

Anyway it is necessary to aim to stable time of the period, differently the meaning of PID regulator is lost.

Also I plan to build test system for testing algorithms.

P.S. Sorry for my English (I'm a little using the automated translator)

**Comment by kizniche** [comment]
I think I figured out how to fix all this. I already fixed the logging issue. I want to test everything before pushing an update.

**Comment by kizniche** [comment]
I think everything should be working correctly. Give it a test and let me know what you find. Thanks for helping fix this issue.

**Comment by kizniche** [comment]
My initial testing it showing an improvement in regulation.

**Pull request merged**
