### PR TITLE
Initial work

### PR DESCRIPTION
**Pull request by David-OConnor**
WIP on adding the [AnyLeaf pH module](http://localhost:8000/ph-module). Need to familiarize myself more with how the API works, and update the `anyleaf_ph_orp.py` file, then test.

This module can connect to either a pH or ORP sensor, but only one at a time. Should there be two separate files under `inputs`? Is the approach I used (`is_enabled(x)`), for when multiple sensors can be connected at ones? Thank you.

### CODE REVIEW

**Comment by kizniche** [comment]
I would create two separate files. is_enabled() is used to determine which measurement channels the user has selected and can both be enabled at the same time, which would cause issues with this module. Measurement channels should only be measurements that can be obtained from a particular hardware setup, so in this case each module would only have one available measurement.

**Comment by kizniche** [comment]
I see your dependency tuple is missing the third string.

```
('pip-pypi', 'anyleaf')
```

Should be

```
('pip-pypi', 'anyleaf', 'anyleaf')
```

**Comment by kizniche** [comment]
Also, you don't have to worry about modifying the documentation, as it's automatically generated from the information in the modules.

**Comment by David-OConnor** [comment]
Thank you. Those two things are fixed. Working through some more.

**Comment by kizniche** [comment]
The type you probably want for the custom_option calibration values are "float", not "tuple"

**Comment by kizniche** [comment]
"tuple" isn't a supported type, so you'll have to break each up into three distinct user inputs.

**Comment by David-OConnor** [comment]
Thank you; fixed. Do you know what could cause this error ? 👍 
```python
  File "/home/pi/Mycodo/mycodo/mycodo_flask/templates/pages/form_options/Measurements_Convert.html", line 26, in top-level template code
    <input class="form-control btn btn-primary btn-sm btn-block" type="button" onclick="setClipboard('{{each_measurement.unique_id}}')" title="UUID: {{each_measurement.unique_id}}, {{dict_translation['copy_to_clipboard']['phrase']}}" value="{% if each_measurement.channel != None %}CH{{each_measurement.channel}} {% endif %}{{dict_measurements[each_measurement.measurement]['name']}} ({{dict_units[each_measurement.unit]['unit']}})">
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'collections.OrderedDict object' has no attribute 'ORP'
```

Got a similar one for `pH` too, after adding either of the modules. Presumably it needs to find the unit somewhere it's missing.

**Comment by kizniche** [comment]
Your measurement must be present in config_devices_units.py:

https://github.com/kizniche/Mycodo/blob/2c2f30c4bf225cfad128ddb35ca465c10fd4070a/mycodo/config_devices_units.py#L152-L155

So, it should be oxidation_reduction_potential

**Comment by kizniche** [comment]
Another thing, if your input type is float, you'll need to change the default value to a float as well:

```
'default_value': (0.18, 4., 23.),
```

to

```
'default_value': 0.18,
```

**Comment by David-OConnor** [comment]
Thank you for all the help. The code now works! 2 lingering questions:

1: Is there a way I could execute a calibration procedure, where the user clicks a button in the Input settings, and values are stored to the `InputModule`'s class values?

2: How would I modify this code (from the bottom of the pH Input) to support using values from an offboard sensor? I think I'm close:

```python
if self.input_dev.temp_source:
    self.value_set(0, self.sensor.read(
        OffBoard(self.input_dev.temp_source.get_last_measurement())
    )
else:
    self.value_set(0, self.sensor.read(OnBoard()))
```

Thank you.

**Comment by kizniche** [comment]
I just merged the multi_channel_output branch I've been working on, which slightly changes how Input modules operate, so there will need to be some tweaks to your module. But, I can do this before I make a release.

> Is there a way I could execute a calibration procedure, where the user clicks a button in the Input settings, and values are stored to the ```InputModule's``` class values?

Yes. See the "custom_actions" dictionary in [mh_z19.py](https://github.com/kizniche/Mycodo/blob/52590a40c2a6c1e674218b1c199f8e5a0e03874c/mycodo/inputs/mh_z19.py), which creates two buttons and an integer input. Notice there are class functions with the same name as the button id. When the button is pressed, it passes the input to the function with the same name as the button. From this function, you can access self to change any variables.

> How would I modify this code (from the bottom of the pH Input) to support using values from an offboard sensor?

What do you mean by offboard sensor?

**Comment by David-OConnor** [comment]
Thank you! Diving into this example.

Some measurements, like pH, are temperature dependent. In this case, it would be reading a different sensor connected to Mycodo, and using its value to help adjust the pH measurement.

**Comment by kizniche** [comment]
> Some measurements, like pH, are temperature dependent. In this case, it would be reading a temperature sensor connected to Mycodo, and using this value to help adjust the pH measurement.

Ah, so you want to select another Input measurement to be able to pass the latest measurement to the pH read function... Take a look at the "custom_options" of [atlas_ph.py](https://github.com/kizniche/Mycodo/blob/52590a40c2a6c1e674218b1c199f8e5a0e03874c/mycodo/inputs/atlas_ph.py), specifically the input selection "temperature_comp_meas", which does exactly this. You'll be able to access the latest measurement from whichever input measurement is selected with:

https://github.com/kizniche/Mycodo/blob/52590a40c2a6c1e674218b1c199f8e5a0e03874c/mycodo/inputs/atlas_ph.py#L144-L147

**Comment by kizniche** [comment]
```self.get_last_measurement()``` will return None if there wasn't a measurement that could be found within the max_age (seconds).

**Comment by David-OConnor** [comment]
Thanks again! Did as you asked, and got calibration to work! Punting temp compensation for now, as it's not that important due to the onboard sensor. What needs to be changed to make compatible with the new PR? 

Ready for review / merge etc, other than the updates.

**Comment by kizniche** [comment]
I was mistaken that Inputs were affected by the feature update. It was only Outputs. I'll review tomorrow or this weekend. Thanks.

**Comment by kizniche** [comment]
When self.get_last_measurement() is successful, it will return a list of the timestamp and value, so ```temp_data = OffBoard(last_temp_measurement)``` should be ```temp_data = OffBoard(last_temp_measurement[1])```. I would also add an ```if last_temp_measurement:``` before that line to check there is indeed a measurement returned. This would also necessitate different logic to resort to calling ```temp_data = OnBoard()```.

> todo: Including this input will raise an error about `cannot convert string to float`

When/how does this error occur?

**Comment by kizniche** [comment]
> todo: Still loses all cal data on deactivation.

Do you need to store calibration values in the database for retrieval after deactivation? Do you need just one tuple of measured voltage and buffer mV or multiple tuples for several points? If so, we can create a dictionary that can be stored with other values in the "custom_options" database column that can be retrieved later.

**Comment by David-OConnor** [comment]
`last_measurement` problems: Fixed.

The `cannot convert string to float` shows at the top of the screen in orange upon hitting one of the calibration buttons, if the dict entry in question is uncommented. It seems odd to me.

I was hoping to store the calibration data in a way that would persist through the device's life. I tried two approaches: 1 - use the library's own struct (eg `self.sensor.cal_1` etc), then tried storing under the `InputModule` class (Current approach). Both dump on deactivation. This is ok, but not ideal. It sounds like the `custom_options` db column is the way to go. In the most general sense, I need to store 2 floats for ORP, and 9 for pH. (ORP, voltage for ORP, and 3 separate points of pH, Voltage, temperature for pH)

**Comment by David-OConnor** [comment]
What's the command to write to the `custom_options` db column? Thank you.

**Comment by kizniche** [comment]
I'm currently deciding if I want to refactor the Input framework like I did with Outputs. When I initially designed Inputs, there was no ability to import custom modules, so I could modify the SQLite database whenever I needed to when adding a new Input. To allow users to create their own modules and store their own settings, I added the custom_options database column for variables to be stored. However, I implemented this as comma separated values rather than something more logical like JSON. Since custom Outputs were relatively new, I don't mind changing the format to use JSON, which is what their custom options currently use. However, there are a lot of users that have custom Input modules using the old CSV format. I'd like to find a way to convert all the current built-in modules to use JSON while allowing backward compatibility with the old format that users currently have for their custom modules. This new JSON format makes it much easier to get/modify/save the database entry over the old format. It also preserves the types (integer, float, etc.) which CSV does not, precluding the need to cast the string from the CSV to these types upon the input initialization.

So, before I develop code for you to be able to change the custom_options database entry for the old format, I'm going to see if I can update to using JSON custom_options for Inputs, which would make it easier for both of us.

**Comment by David-OConnor** [comment]
Awesome. I'm happy with it the way it is now as a start. Can always modify later to store the calibration info in the database.

**Comment by kizniche** [comment]
Well, it was a relatively easy change, and I believe I've preserved backward-compatibility with current custom Input modules. So, with the next release, you should be able to get and modify custom options within Input modules with the following code:

```python
import json
from mycodo.config import SQL_DATABASE_MYCODO
from mycodo.databases.models import Input
from mycodo.databases.utils import session_scope

MYCODO_DB_PATH = 'sqlite:///' + SQL_DATABASE_MYCODO

dict_custom_options = json.loads(self.input_dev.custom_options)
if 'my_new_option' in dict_custom_options:
    self.logger.info("Value for my_new_option: {}".format(
        dict_custom_options['my_new_option']))
else:
    dict_custom_options['my_new_option'] = 12.5
str_custom_options = json.dumps(dict_custom_options)
with session_scope(MYCODO_DB_PATH) as new_session:
    mod_input = new_session.query(Input).filter(
        Input.unique_id == self.unique_id).first()
    mod_input.custom_options = str_custom_options
    new_session.commit()
```

**Comment by David-OConnor** [comment]
Awesome!

**Comment by kizniche** [comment]
I should actually turn this into function in the base input class: get_custom_option(), set_custom_option()

**Comment by kizniche** [comment]
So, I've incorporated that code into the base Input class, so all you will need to do to get and set values in the custom_options column of the database is:

```python
set_custom_option("my_option", 15.5)
my_option_value = get_custom_option("my_option")
```

**Comment by David-OConnor** [comment]
Updated to use this style, but haven't tested yet. Likely will have small bugs.

**Comment by David-OConnor** [comment]
Something's fucked with the commit files; don't have time to fix now.

**Comment by kizniche** [comment]
Keep in mind self.get_custom_option() will return None if the value isn't found in the database, so I don't know if you want to add a check or just pass it to the class as you currently have it.

**Comment by David-OConnor** [comment]
I've updated it, but currently not working. Fields are initializing to empty, not the set `default_value`.

**Comment by kizniche** [comment]
I'll give them a test and see what's wrong.

**Comment by kizniche** [comment]
I was able to test the ORP module and here are a few comments:

1. I would recommend adding the dependency ```('apt', 'python3-numpy', 'python3-numpy')```, ```('apt', 'python3-scipy', 'python3-scipy')```, and ```('apt', 'python3-matplotlib', 'python3-matplotlib')``` before the pypi dependencies, because the library you're using requires numpy/scipy, and compiling the latest versions take forever on a Pi (and after writing this and waiting for the install to finish, it actually errored, so apt is the way to go).
2. I fixed default values not displaying for custom actions (b3d3c46).

**Comment by kizniche** [comment]
I'm ready to release 8.8.0, but I'd like to include these in the release. Are these ready to go? I can merge and add the apt dependencies myself, but if you have any other changes you haven't pushed, let me know. I also noticed some minor formatting issues: missing closing parentheses in action title, action titles very long.

**Comment by David-OConnor** [comment]
Great. I'll set it up now and make sure it works with the new calibration system.

**Comment by David-OConnor** [comment]
Note that I had to add to my own Python/Pi drivers to apt install scipy. It's nice mycodo will do that automatically.

**Comment by David-OConnor** [comment]
Do you know what would cause this error? 

```python
  File "/home/pi/Mycodo/mycodo/inputs/anyleaf_ph.py", line 222, in initialize_input
    self.get_custom_option("cal1_v_internal"),
AttributeError: 'InputModule' object has no attribute 'get_custom_option'

```

**Comment by kizniche** [comment]
Are you on the latest commit of the Mycodo master branch?

**Comment by David-OConnor** [comment]
Yea - and I can confirm the method is in the `AbstractBaseInput`. Weird.

**Comment by David-OConnor** [comment]
Latest error after clean install, + updating the `BaseInput` file only:

```python
 File "/home/pi/Mycodo/mycodo/inputs/anyleaf_ph.py", line 222, in initialize_input
    self.get_custom_option("cal1_v_internal"),
  File "/var/mycodo-root/mycodo/inputs/base_input.py", line 306, in get_custom_option
    dict_custom_options = json.loads(self.input_dev.custom_options)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-09-09 00:55:45,689 - INFO - mycodo.controllers.controller_input_b768177f - Activated in 2063.9 ms
2020-09-09 00:55:45,690 - ERROR - mycodo.controllers.controller_input_b768177f - Error while attempting to read input: 'NoneType' object has no attribute 'next'
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/controllers/controller_input.py", line 391, in update_measure
    measurements = self.measure_input.next()
AttributeError: 'NoneType' object has no attribute 'next'
```

**Comment by kizniche** [comment]
cloning master now to test an install

**Comment by kizniche** [comment]
> Do you know what would cause this error?

I can't replicate this error. You're likely not running the latest code. Here's how you can preserve your current install and test the latest commit:

```
sudo service mycodo stop && sudo service mycodoflask stop
cd ~
sudo mv Mycodo Mycodo-backup
git clone https://github.com/kizniche/Mycodo
sudo bash ~/Mycodo/install/setup.sh
```

After the install, copy the input module, restart the frontend and backend, and test. When done, this is how you restore your backup:

```
sudo service mycodo stop && sudo service mycodoflask stop
cd ~
sudo mv Mycodo Mycodo-test-backup
sudo mv Mycodo-backup Mycodo
sudo bash ~/Mycodo/mycodo/scripts/upgrade_post.sh
```

Then, you can reboot and your old version should be running.
```

**Comment by David-OConnor** [comment]
Now I'm getting this:

```python
InputModule raised an exception when taking a reading: unsupported operand type(s) for /: 'NoneType' and 'NoneType'
```

Odd it doesn't point to a line. It gets through the init, and throws this at the `self.sensor.read()` line. Attempting to troubleshoot's very odd too. For example, anytime I try to `self.logger.log` something from `get_custom_option()`, ti refuses to print that line!

For example, bottom of `initialize_input`:
```python
        a = self.get_custom_option("cal_v")
        self.logger.error("Prints")
        self.logger.error("Doesn't print", a)
```

**Comment by kizniche** [comment]
Does this work?

```python
self.set_custom_option("test_1", 100)
self.logger.info("value: {}".format(self.get_custom_option("test_1")))
```

**Comment by David-OConnor** [comment]
Yep - that logs

**Comment by kizniche** [comment]
> Odd it doesn't point to a line.

If you enable the Input option Log Level Debug it will log that as an exception rather than merely an error, and it will show the whole traceback.

**Comment by David-OConnor** [comment]
Ooh. It looks like that fixed my logging problem. And we're almost there! Using your new logging, it's initializing the custom options to None. That's all. If I set them, eg by running a cal, it works again until deleting and re-adding the device.

**Comment by kizniche** [comment]
Yeah, if the value isn't set, it (returns None](https://github.com/kizniche/Mycodo/pull/825#issuecomment-685090706). The Default Value is merely used for the frontend form. Checks should be made if None is an unacceptable value to receive.

**Comment by David-OConnor** [comment]
Thank you very much for working with me on this. Tested on my end and all works!

**Comment by kizniche** [comment]
You're welcome. It's always nice to see people contribute. I like to help when I can.

**Pull request merged**
